spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mcm
    username: postgres
    password: postgres
    sql-script-encoding: UTF-8
logging:
  file: logs/logback.log
server:
  context-path: /mcm
settings:
  firebase:
    api-name: mcm-client
    service-account: classpath:path/to/mcm-client-firebase-adminsdk-0hzb6-b1fb766d6a.json
    database-url: https://mcm-client.firebaseio.com
  scraping:
    images:
      street-fashion-snap-url: https://street-fashion-snap.com/tagged/%E3%83%A1%E3%83%B3%E3%82%BA/page/