spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mcm
    username: postgres
    password: postgres
    sql-script-encoding: UTF-8
  jpa:
    show-sql: true

logging:
  file: logs/logback.log
  level:
    org:
      hidernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace
          EnumType: trace

server:
  context-path: /mcm

settings:
  firebase:
    web-url: http://localhost:8888
    api-name: mcm-client
    service-account: classpath:path/to/mcm-client-firebase-adminsdk-0hzb6-b1fb766d6a.json
    database-url: https://mcm-client.firebaseio.com