version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "build.gradle" }}
            - v1-dependencies-{{ .Branch }}-
            - v1-dependencies-
      - run: gradle dependencies
      - run: gradle build
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ .Branch }}-{{ checksum "build.gradle" }}
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .
  deploy:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo
    steps:

      - attach_workspace:
          at: ~/repo

      - add_ssh_keys:
          fingerprints:
            - "a1:f6:4b:d0:98:7b:cb:43:df:13:e4:cd:86:75:c0:c0"
      - run : sudo apt install -y rsync
      - run : ssh-keyscan ${HOST_NAME} >> ~/.ssh/known_hosts
      - run : echo "$PROD_YAML" > ./src/main/resources/application-prod.yml
      - run : gradle build
      - deploy:
          name: masterをdeploy
          command: |
            ssh ${USER_NAME}@${HOST_NAME} "service ${APP_NAME} stop"
            rsync -vc ${BUILD_APP} ${USER_NAME}@${HOST_NAME}:${APP_DIR}
            ssh ${USER_NAME}@${HOST_NAME} "service ${APP_NAME} start"
workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
