package source.domain.logging;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum LoggingHead {
    START("[API START]"),
    END("[API END]"),
    RESOURCES("[API RESOURCES]"),
    INPUT("[API INPUT]"),
    ACTION("[API ACTION]"),

    LOGIN("[LOGIN]"),

    ROUTING("[ROUTING]"),

    BRAND_CREATE("[BRAND CREATE]"),
    BRAND_UPDATE("[BRAND UPDATE]"),
    BRAND_DELETE("[BRAND DELETE]"),
    BRAND_RESTORATION("[BRAND RESTORATION]"),

    CLOTHES_CREATE("[CLOTHES CREATE]"),
    CLOTHES_UPDATE("[CLOTHES UPDATE]"),
    CLOTHES_DELETE("[CLOTHES DELETE]"),
    CLOTHES_RESTORATION("[CLOTHES RESTORATION]"),

    COORDINATE_CREATE("[COORDINATE CREATE]"),
    COORDINATE_UPDATE("[COORDINATE UPDATE]"),
    COORDINATE_DELETE("[COORDINATE DELETE]"),

    SHOP_CREATE("[SHOP CREATE]"),
    SHOP_UPDATE("[SHOP UPDATE]"),
    SHOP_DELETE("[SHOP DELETE]"),
    SHOP_RESTORATION("[SHOP RESTORATION]"),

    GENRE_CREATE("[GENRE CREATE]"),
    GENRE_UPDATE("[GENRE UPDATE]"),
    GENRE_DELETE("[GENRE DELETE]")
    ;

    private String key;
}
